apiVersion: v1
kind: Service
metadata:
  labels:
     app: ticketing-ui
  name: ticketing-ui
  namespace: ticketing
spec:
  type: LoadBalancer
  ports:
  - name: "ticketing-service"
    port: 5000
    targetPort: 5000
  selector:
    app: ticketing-ui


