apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ticketing
spec:
  type: NodePort
  selector:
    service: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
